package backtest

import (
	"context"
	"fmt"
	"time"

	"github.com/Guy2co/algo-crypto-trader-bot/internal/config"
	"github.com/Guy2co/algo-crypto-trader-bot/internal/exchange"
	mocexchange "github.com/Guy2co/algo-crypto-trader-bot/internal/exchange/mock"
	"github.com/Guy2co/algo-crypto-trader-bot/internal/strategy"
	"go.uber.org/zap"
)

// Engine drives a Strategy against a historical candle feed.
type Engine struct {
	cfg      *config.Config
	feed     *CandleFeed
	mock     *mocexchange.Exchange
	strategy strategy.Strategy
	logger   *zap.Logger
}

// NewEngine creates a backtest Engine.
func NewEngine(cfg *config.Config, strat strategy.Strategy, feed *CandleFeed, logger *zap.Logger) *Engine {
	balances := map[string]exchange.Balance{
		"USDT": {Asset: "USDT", Free: cfg.Backtest.InitialBalanceUSDT},
		"BTC":  {Asset: "BTC", Free: 0},
	}
	mock := mocexchange.New(balances, cfg.Backtest.FeeRate)
	// Set initial price so strategies can query it during Init.
	if len(feed.Candles()) > 0 {
		mock.SetPrice(feed.Candles()[0].Open)
	}
	return &Engine{
		cfg:      cfg,
		feed:     feed,
		mock:     mock,
		strategy: strat,
		logger:   logger,
	}
}

// Run executes the full backtest simulation and returns a Report.
func (e *Engine) Run(ctx context.Context) (*Report, error) {
	// Subscribe to fill events from the mock exchange.
	fillChan, cancelStream, err := e.mock.SubscribeOrderFills(ctx, e.cfg.Backtest.Symbol)
	if err != nil {
		return nil, fmt.Errorf("subscribe order fills: %w", err)
	}
	defer cancelStream()

	// Initialize the strategy.
	if err = e.strategy.Init(ctx, e.mock); err != nil {
		return nil, fmt.Errorf("strategy init: %w", err)
	}

	candles := e.feed.Candles()
	if len(candles) == 0 {
		return nil, fmt.Errorf("no candles loaded")
	}

	// Apply date filters.
	filtered, err := e.filterCandles(candles)
	if err != nil {
		return nil, err
	}

	var (
		equityCurve []EquityPoint
		totalTrades int
	)

	baseAsset := e.cfg.Grid.BaseAsset

	for _, candle := range filtered {
		// Simulate fills for this candle.
		e.mock.SimulateFills(candle)

		// Process all fill events generated by this candle.
		for {
			var event exchange.OrderFillEvent
			select {
			case event = <-fillChan:
			default:
				goto doneProcessing
			}
			totalTrades++
			if fillErr := e.strategy.OnFill(ctx, e.mock, event); fillErr != nil {
				e.logger.Warn("strategy OnFill error", zap.Error(fillErr))
			}
		}
	doneProcessing:

		equity := e.mock.TotalEquityUSDT(baseAsset)
		equityCurve = append(equityCurve, EquityPoint{
			Time:   candle.CloseTime,
			Equity: equity,
		})
	}

	if err = e.strategy.Stop(ctx, e.mock); err != nil {
		e.logger.Warn("strategy stop error", zap.Error(err))
	}

	// Read grid metrics if accessible via OnTick to get cycle count.
	// We call OnTick once to log final state.
	_ = e.strategy.OnTick(ctx, e.mock)

	finalEquity := e.mock.TotalEquityUSDT(baseAsset)
	e.logger.Info("backtest complete",
		zap.Float64("initial_usdt", e.cfg.Backtest.InitialBalanceUSDT),
		zap.Float64("final_usdt", finalEquity),
		zap.Int("total_trades", totalTrades),
	)

	return computeReport(
		e.cfg.Backtest.Symbol,
		e.cfg.Backtest.InitialBalanceUSDT,
		equityCurve,
		totalTrades,
		0,    // cycle count from strategy state would require type assertion
		0,    // fees from strategy state
	), nil
}

func (e *Engine) filterCandles(candles []exchange.Candle) ([]exchange.Candle, error) {
	var start, end time.Time
	var err error

	if e.cfg.Backtest.StartDate != "" {
		start, err = time.Parse("2006-01-02", e.cfg.Backtest.StartDate)
		if err != nil {
			return nil, fmt.Errorf("parse start_date: %w", err)
		}
	}
	if e.cfg.Backtest.EndDate != "" {
		end, err = time.Parse("2006-01-02", e.cfg.Backtest.EndDate)
		if err != nil {
			return nil, fmt.Errorf("parse end_date: %w", err)
		}
		end = end.Add(24 * time.Hour) // include the end day
	}

	filtered := make([]exchange.Candle, 0, len(candles))
	for _, c := range candles {
		if !start.IsZero() && c.OpenTime.Before(start) {
			continue
		}
		if !end.IsZero() && c.OpenTime.After(end) {
			continue
		}
		filtered = append(filtered, c)
	}
	return filtered, nil
}
